### ISSUE TITLE
Organization Svc - Rename API Methods 

### ISSUE THREAD

**Issue by dudikrisher** [scalecube/scalecube-organization-service#115]
Rename the below API methods: 
addOrganizationApiKey -->addApiKey
deleteOrganizationApiKey --> deleteApiKey
getUserOrganizationsMembership --> getMyOrganizations
updateOrganizationMemberRole --> updateMemberRole
create -->createOrganization
delete --> deleteOrganization

**Comment by PavloPetrina** [comment]
Tested Ok on `staging`:
Renamed API methods:
addOrganizationApiKey -->addApiKey
deleteOrganizationApiKey --> deleteApiKey
>https://monosnap.com/file/tFe0QxqcUhsQJzUDn5wWYVUS9W7dbm

getUserOrganizationsMembership --> getMyOrganizations
updateOrganizationMemberRole --> updateMemberRole
>https://monosnap.com/file/g56d6geMihYOda5aH5MZ5YhGEFg1cw

create -->createOrganization
delete --> deleteOrganization
>https://monosnap.com/file/DdrnoIXaD93P3SWQ5w3l5PcuaNtRBz

**Comment by dudikrisher** [comment]
Did you fixed the apiDoc?

**Comment by PavloPetrina** [comment]
@dudikrisher  of course ) : https://github.com/scalecube/scalecube-organization-service/pull/121/files
