### ISSUE TITLE
Error is returned upon getUserOrganizationsMembership method is performed	

### ISSUE THREAD

**Issue by PavloPetrina** [scalecube/scalecube-organization-service#119]
STR 

1. Create the Org 
2. As the owner of this Org get to know your Membership > **getUserOrganizationsMembership**

AR: NDEXes which were created and stored on single node are not shared between the other cluster nodes
{code:java} 
{"sig":2,"q":"/io.scalecube.services.error/500","sid":1,"d":{"errorCode":500,"errorMessage":"N1QL error: {\"msg\":\"No index available on keyspace organizations that matches your query. Use CREATE INDEX or CREATE PRIMARY INDEX to create an index, or check that your expected index is online.\",\"code\":4000}"}} 
{code} 

ER: Each Org member could get own membership

Related issue https://jivygroup.atlassian.net/browse/MPA-7812 > History 21/03/19 11:46:44

**Comment by dmytro-lazebnyi** [comment]
The cause of the problem is that primary index for `organizations` bucket was deleted.
Need to add the following queries to Couchbase deployment process:
```
create primary index org_primary_1 on organizations with {"nodes": ["couchbase1.couchbase.svc.cluster.local:8091"]};
create primary index org_primary_2 on organizations with {"nodes": ["couchbase2.couchbase.svc.cluster.local:8091"]};
create primary index org_primary_3 on organizations with {"nodes": ["couchbase3.couchbase.svc.cluster.local:8091"]};
```

**Comment by PavloPetrina** [comment]
Tested OK on wss://configuration-service-ws.genesis.om2.com

**Comment by PavloPetrina** [comment]
Tested Ok on `master` wss://configuration-service-ws.genesis.om2.com
