### ISSUE TITLE
Reuse couchbase environments (cluster)

### ISSUE THREAD

**Issue by dmytro-lazebnyi** [scalecube/scalecube-organization-service#70]
During starting of `scalecube-organization-service` couchbase client warns:

> W 2019-01-11T11:47:55,972 c.c.c.c.e.CoreEnvironment More than 1 Couchbase Environments found (2), this can have severe impact on performance and stability. Reuse environments! [main]

See related code:
```java
    adminCluster = nodes.isEmpty() ? CouchbaseCluster.create() : CouchbaseCluster.create(nodes);
    adminCluster.authenticate(settings.getCouchbaseUsername(), settings.getCouchbasePassword());
    cluster = nodes.isEmpty() ? CouchbaseCluster.create() : CouchbaseCluster.create(nodes);
```
https://github.com/scalecube/scalecube-organization-service/blob/master/scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseRepositoryFactory.java#L24-L26

**Comment by dudikrisher** [comment]
@dmytro-lazebnyi  can we close this?
